# Bab 2 Penyelenggara Akreditasi Rumah Sakit {-}

## A.	Persiapan  Akreditasi {-}

Persiapan dilakukan sepenuhnya oleh rumah sakit secara  mandiri atau dengan pembinaan dari Kementerian Kesehatan, dinas kesehatan daerah provinsi, dan dinas kesehatan daerah kabupaten/kota maupun lembaga lain yang kompeten. Kegiatan persiapan akreditasi antara lain pemenuhan syarat untuk dapat diakreditasi dengan pemenuhan kelengkapan dokumen pelayanan dan perizinan, peningkatan kompetensi staf melalui pelatihan, dan kesiapan fasilitas pelayanan sesuai dengan peraturan perundang-undangan.

Rumah Sakit dapat melakukan penilaian mandiri secara periodik tentang pemenuhan standar akreditasi rumah sakit sehingga tergambar kemampuan rumah sakit dalam memenuhi standar akreditasi yang ditetapkan. Setelah dinilai mampu oleh pimpinan rumah sakit,  maka rumah sakit dapat mengajukan permohonan survei kepada lembaga independen penyelenggara akreditasi yang dipilih oleh rumah sakit. Pemilihan lembaga dilaksanakan secara sukarela oleh rumah sakit dan tidak atas paksaan pihak manapun.

Rumah sakit yang mengajukan permohonan survei akreditasi paling sedikit harus memenuhi persyaratan sebagai berikut:

1.	Rumah sakit memiliki perizinan berusaha yang masih berlaku dan teregistrasi di Kementerian Kesehatan;
2.	Kepala atau direktur rumah sakit harus seorang tenaga medis yang mempunyai kemampuan dan keahlian di bidang perumahsakitan;
3.	Rumah sakit memiliki Izin Pengelolaan Limbah Cair (IPLC)  yang masih berlaku;
4.	Rumah sakit memiliki kerja sama dengan pihak ketiga yang mempunyai izin sebagai pengolah dan/atau sebagai transporter limbah B3 yang masih berlaku atau izin alat pengolah limbah B3;
5.	Seluruh tenaga medis di rumah sakit yang menyelenggarakan pelayanan kesehatan (pemberi asuhan) memiliki Surat Tanda Registrasi (STR) dan Surat Izin Praktik (SIP) yang masih berlaku atau surat tugas sesuai dengan ketentuan peraturan perundang- undangan;
6.	Rumah sakit bersedia melaksanakan kewajiban dalam meningkatkan mutu dan keselamatan pasien; dan
7.	Pemenuhan Sarana Prasarana dan Alat Kesehatan  (SPA)  minimal 60% berdasarkan ASPAK dan telah tervalidasi 100% oleh Kementerian Kesehatan atau dinas kesehatan daerah setempat sesuai dengan kewenangannya.

## B.	Pelaksanaan Penilaian Akreditasi {-}

Lembaga independen penyelenggara akreditasi melaksanakan penilaian persyaratan rumah sakit yang mengajukan permohonan kemudian Lembaga menetapkan waktu pelaksanaan akreditasi setelah persyaratan dipenuhi rumah sakit. Penilaian akreditasi dilakukan dengan metode daring dan/atau luring sesuai tahapan pelaksanaan akreditasi. Adapun tahapan pelaksanaan penilaian akreditasi adalah sebagai berikut:

### 1.	Persiapan dan penjelasan survei {-}

Pada tahap ini lembaga penyelenggara akreditasi menyampaikan seluruh rangkaian kegiatan akreditasi dimulai dari persiapan survei, pelaksanaan survei dan setelah survei. Penjelasan dapat dilakukan dengan metode daring menggunakan media informasi yang tersedia dan dapat diakses oleh rumah sakit.

### 2.	Penyampaian dan pemeriksaan dokumen {-}

Rumah Sakit menyampaikan dokumen kepada lembaga independen penyelenggara akreditasi melalui sistem informasi yang telah disediakan oleh lembaga independen penyelenggara akreditasi yang bersangkutan. Jenis dokumen yang akan disampaikan oleh rumah sakit mengikuti permintaan dari surveior lembaga independen penyelenggara akreditasi yang disesuaikan dengan standar akreditasi. Lembaga independen penyelenggara akreditasi melakukan evaluasi dan analisis dokumen dan melakukan klarifikasi kepada rumah sakit terhadap dokumen-dokumen tersebut. Kegiatan ini dilakukan secara daring menggunakan sistem informasi yang dapat diakses oleh rumah sakit.

### 3.	Telusur dan kunjungan lapangan {-}

Telusur dan kunjungan lapangan dilakukan oleh lembaga independen penyelenggara akreditasi setelah melakukan klarifikasi dokumen yang disampaikan oleh rumah sakit. Telusur dan kunjungan lapangan bertujuan untuk memastikan kondisi lapangan sesuai dengan dokumen yang disampaikan, serta untuk mendapatkan hal-hal yang masih perlu pembuktian lapangan oleh surveior. Pada saat telusur, surveior akan melakukan observasi, wawancara staf, pasien, keluarga, dan pengunjung serta simulasi.

Lembaga independen penyelenggara akreditasi menentukan jadwal pelaksanaan telusur dan kunjungan lapangan. Jumlah hari dan jumlah surveior yang melaksanakan telusur dan kunjungan lapangan sesuai dengan ketentuan sebagai berikut:

| Klasifikasi RS | Kelas RS | Jumlah   Hari | Jumlah Surveior |
|----------------|:--------:|:-------------:|:---------------:|
| RS Umum        |     A    |       3       |        4        |
|                |     B    |       2       |        3        |
|                |     C    |       2       |        2        |
|                |     D    |       2       |        2        |
| RS Khusus      |     A    |       2       |        3        |
|                |     B    |       2       |        2        |
|                |     C    |       2       |        2        |


### 4.	Penilaian {-}

Lembaga independen penyelenggara akreditasi menetapkan tata cara dan tahapan penilaian akreditasi dengan berpedoman pada standar akreditasi yang dipergunakan saat survei akreditasi. Tahapan penilaian ditentukan lembaga independen penyelenggara akreditasi dengan menerapkan prinsip-prinsip keadilan, profesionalisme, dan menghindari terjadinya konflik kepentingan. Lembaga independen penyelenggara akreditasi membuat instrumen, daftar tilik dan alat bantu untuk surveior dalam melakukan penilaian agar hasil yang diperoleh objektif dan dapat dipertanggungjawabkan.

Penentuan skor dari elemen penilaian dilakukan dengan memperhatikan kelengkapan dokumen, hasil telusur, kunjungan lapangan, simulasi kepada petugas, wawancara, dan klarifikasi yang ada di standar akreditasi mengikuti ketentuan sebagai berikut:

| No | Kriteria                                                                                                                                                                                                                               | Skor 10 (TL)                                                                                                                                                                                                                                             | Skor 5 (TS)                                                                                                                                                                                                                                                                                                                                        | Skor 0 (TT)                                                                                                                                                  | TDD                    |
|----|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------|
| 1  | Pemenuhan elemen penilaian                                                                                                                                                                                                             | ≥80%                                                                                                                                                                                                                                                     | 20% s.d <80%                                                                                                                                                                                                                                                                                                                                       | <20%                                                                                                                                                         | Tidak dapat diterapkan |
| 2  | Bukti kepatuhan                                                                                                                                                                                                                        | Bukti kepatuhan ditemukan secara konsisten  pada semua bagian/unit di mana persyaratan-   persyaratan tersebut berlaku. Catatan: Hasil pengamatan tidak dapat dianggap   sebagai temuan apabila hanya terjadi      pada 1 (satu) pengamatan (observasi). | Bukti kepatuhan ditemukan tidak konsisten/ hanya pada sebagian unit di mana persyaratan-persyaratan tersebut berlaku (misalnya   ditemukan kepatuhan di IRI, namun tidak di IRJ, patuh pada ruang operasi   namun tidak patuh di unit rawat sehari (day surgery), patuh pada area-area   yang menggunakan sedasi namun tidak patuh di klinik gigi) | Bukti kepatuhan tidak ditemukan pada semua bagian/unit di mana                                                                                               |                        |
| 3  | Hasil wawancara dari pemenuhan persyaratan yang ada di   EP                                                                                                                                                                            | Hasil wawancara menjelaskan sesuai standar dan   dibuktikan dengan dokumen dan pengamatan                                                                                                                                                                | Hasil wawancara menjelaskan sebagian sesuai standar dan dibuktikan dengan dokumen dan pengamatan                                                                                                                                                                                                                                                   | Hasil wawancara tidak sesuai standar dan dibuktikan dengan dokumen dan pengamatan                                                                            |                        |
| 4  | Regulasi sesuai dengan yang dijelaskan di maksud dan tujuan pada standar                                                                                                                                                               | Regulasi yang meliputi Kebijakan dan SPO lengkap sesuai   dengan maksud dan tujuan pada standar                                                                                                                                                          | Regulasi yang meliputi Kebijakan dan SPO sesuai dengan maksud dan tujuan pada standar hanya sebagian/tidak lengkap                                                                                                                                                                                                                                 | Regulasi yang meliputi Kebijakan dan SPO sesuai dengan   maksud dan tujuan pada standar tidak ada                                                            |                        |
| 5  | Dokumen rapat/pertemu an: seperti undangan, materi rapat, absensi/daftar hadir, notulen rapat                                                                                                                                          | Kelengkapan bukti dokumen rapat 80% s.d 100% (cross check dengan wawancara)                                                                                                                                                                              | Kelengkapan bukti dokumen rapat 50% s.d <80%                                                                                                                                                                                                                                                                                                       | Kelengkapan bukti dokumen rapat <50%                                                                                                                         |                        |
| 6  | Dokumen pelatihan seperti kerangka acuan (TOR) pelatihan yang dilampiri jadwal acara, undangan, materi/bahan pelatihan, absensi/daftar   hadir, laporan pelatihan                                                                      | Kelengkapan bukti dokumen pelatihan 80% s.d 100%                                                                                                                                                                                                         | Kelengkapan bukti dokumen pelatihan 50% s.d <80%                                                                                                                                                                                                                                                                                                   | Kelengkapan bukti dokumen pelatihan <50%                                                                                                                     |                        |
| 7  | Dokumen orientasi staf seperti kerangka acuan (TOR) orientasi yang dilampiri jadwal acara, undangan, absensi/daftar hadir,   laporan, penilaian hasil orientasi dari kepala SDM (orientasi umum) atau   kepala unit (orientasi khusus) | Kelengkapan bukti dokumen orientasi 80% s.d 100%                                                                                                                                                                                                         | Kelengkapan bukti dokumen orientasi 50% s.d <80%                                                                                                                                                                                                                                                                                                   | Kelengkapan bukti dokumen orientasi <50%                                                                                                                     |                        |
| 8  | Hasil observasi pelaksanaan kegiatan/ pelayanan sesuai regulasi dan standar                                                                                                                                                            | Pelaksanaan kegiatan/ pelayanan sesuai regulasi dan standar 80% s.d 100%. Contoh: 9 dari 10 kegiatan/ pelayanan yang diobservasi sudah memenuhi EP                                                                                                       | Pelaksanaan kegiatan/ pelayanan sesuai regulasi dan standar  50%  s.d <80% Contoh: 5 dari 10 kegiatan/pelayanan yang diobservasi sudah memenuhi EP                                                                                                                                                                                                 | Pelaksanaan kegiatan/ pelayanan sesuai regulasi dan standar <50%. Contoh: hanya 4 dari 10 kegiatan/ pelayanan  yang diobservasi memenuhi EP                  |                        |
| 9  | Hasil simulasi staf sesuai regulasi/ standar                                                                                                                                                                                           | Staf dapat memperagakan/ mensimulasikan sesuai regulasi/ standar: 80% s.d 100%. Contoh: 9 dari 10 staf yang diminta simulasi sudah memenuhi regulasi/standar                                                                                             | Staf  dapat memperagakan/ mensimulasikan sesuai regulasi/ standar 50% s.d <80%. Contoh: 5 dari 10 staf yang diminta simulasi sudah memenuhi   regulasi/standar                                                                                                                                                                                     | Staf  dapat memperagakan/   mensimulasikan sesuai regulasi/ standar <50%. Contoh: hanya 4 dari 10 staf yang diminta simulasi sudah memenuhi regulasi/standar |                        |
| 10 | Kelengkapan rekam medik (Telaah rekam medik tertutup), pada   survei awal 4 bulan sebelum survei, pada survei ulang 12 bulan sebelum survei                                                                                            | Rekam medik lengkap 80% s.d 100% saat di lakukan telaah.  Contoh hasil telaah: 9 dari 10 rekam  medik yang lengkap                                                                                                                                       | Rekam medik lengkap 50% s.d <80% saat di lakukan telaah. Contoh  hasil telaah: 5 dari 10 rekam   medik yang lengkap                                                                                                                                                                                                                                | Rekam medik lengkap kurang dari 50% saat di lakukan   telaah. Contoh  hasil telaah: hanya 4 dari 10 rekam medik yang lengkap                                 |                        |
Keterangan:

TL	:	Terpenuhi Lengkap

TS	:	Terpenuhi Sebagian 

TT	:	Tidak Terpenuhi

TDD :	Tidak Dapat Diterapkan

### 5.	Penutupan {-}

Setelah dilakukan telusur dan kunjungan lapangan termasuk klarifikasi kepada rumah sakit, maka surveior dapat menyampaikan hal-hal penting yang berkaitan dengan pelaksanaan akreditasi kepada rumah sakit secara langsung/luring. Tujuan tahapan  ini adalah untuk memberi gambaran kepada rumah sakit bagaimana proses akreditasi yang telah dilaksanakan dan hal-hal yang perlu mendapat perbaikan untuk meningkatkan mutu pelayanan.
 
## C.	Pasca Akreditasi {-}

### 1.	Hasil Akreditasi dan Akreditasi Ulang {-}

Lembaga independen penyelenggara akreditasi menyampaikan hasil akreditasi kepada Kementerian Kesehatan melalui Direktur Jenderal Pelayanan Kesehatan paling lambat 5 (lima) hari kerja setelah dilakukan survei. Hasil akreditasi berdasarkan pemenuhan standar akreditasi dalam Keputusan Menteri ini, dilaksanakan dengan mengikuti ketentuan sebagai berikut:

| Hasil Akreditasi    | Kriteria                                                                                                                                                                                               |
|---------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Paripurna           | Seluruh Bab mendapat nilai minimal 80%                                                                                                                                                                 |
| Utama               | 12 – 15 Bab mendapatkan nilai 80% dan Bab SKP mendapat nilai minimal 80%. Untuk rumah sakit selain rumah sakit pendidikan/wahana pendidikan maka kelulusan adalah 12 – 14 bab dan bab SKP minimal 80 % |
| Madya               | 8 sampai 11 Bab   mendapat nilai minimal   80% dan Bab   SKP mendapat   nilai minimal 70%                                                                                                              |
| Tidak Terakreditasi | a. Kurang dari 8 Bab yang mendapat nilai minimal 80%; dan/atau  b. Bab SKP mendapat nilai kurang dari 70%                                                                                              |

Rumah sakit diberikan kesempatan mengulang pada standar yang pemenuhannya kurang dari 80%. Akreditasi ulang dapat dilakukan paling cepat 3 (tiga) bulan dan paling lambat 6 (enam) bulan sejak survei terakhir dilaksanakan.

### 2.	Penyampaian Sertifikat Akreditasi {-}

Penyampaian sertifikat akreditasi rumah sakit dilakukan paling lambat 14 (empat belas) hari setelah survei akreditasi dilakukan. Sertifikat akreditasi mencantumkan masa berlaku akreditasi sesuai dengan ketentuan peraturan perundang-undangan.

### 3.	Penyampaian Rekomendasi {-}

Rekomendasi hasil penilaian akreditasi disampaikan oleh lembaga independen penyelenggara akreditasi kepada rumah sakit berisikan hal-hal yang harus ditindaklanjuti atau diperbaiki oleh rumah sakit. Penyampaian rekomendasi dilakukan bersamaan dengan penyerahan sertifikat akreditasi.

### 4.	Penyampaian Rencana perbaikan {-}

Rumah sakit membuat Perencanaan Perbaikan Strategi (PPS) berdasarkan rekomendasi yang disampaikan oleh  lembaga penyelenggara akreditasi. Penyampaian rencana perbaikan dilakukan dalam waktu  45  (empat  puluh  lima)  hari  sejak  menerima rekomendasi dari lembaga penyelenggara akreditasi. Strategi rencana perbaikan disampaikan kepada lembaga yang melakukan akreditasi, dinas kesehatan setempat untuk rumah sakit kelas B, kelas C  dan Kelas D, dan untuk rumah sakit kelas A disampaikan ke Kementerian Kesehatan.

### 5.	Penyampaian Laporan Akreditasi {-}

Lembaga menyampaikan pelaporan kegiatan akreditasi kepada Kementerian Kesehatan melalui sistem informasi akreditasi rumah sakit. Laporan berisi rekomendasi perbaikan yang harus dilakukan oleh rumah sakit, dan tingkat akreditasi yang dicapai oleh  rumah sakit. Laporan kegiatan akreditasi dalam sistem informasi tersebut dapat diakses oleh pemerintah daerah provinsi dan dinas kesehatan daerah kabupaten/kota.

### 6.  Umpan Balik Pelaksanaan  Survei  Akreditasi  Oleh  Rumah  Sakit {-}

Untuk menjamin akuntabilitas dan  kualitas  pelaksanaan  survei, maka setiap survei harus diikuti dengan permintaan umpan balik kepada rumah sakit terkait penyelenggaraan survei akreditasi dan kinerja dan perilaku surveior. Umpan balik disampaikan kepada lembaga	independen	penyelenggara	akreditasi	di	rumah	sakit tersebut	dan	Kementerian	Kesehatan	melalui	sistem	informasi akreditasi rumah sakit. Umpan balik digunakan sebagai dasar untuk upaya	peningkatan	kualitas	penyelenggaraan	survei	akreditasi. Kementerian Kesehatan dapat memanfaatkan informasi dari umpan balik	tersebut	untuk	melakukan	pembinaan	dan	pengawasan penyelenggaraan	survei	akreditasi	kepada lembaga	independen penyelenggara akreditasi rumah sakit.