# D.	Program Nasional {-}

**Gambaran Umum**

Pada Rencana Pembangunan Jangka Menengah Nasional (RPJMN) bidang kesehatan telah ditentukan prioritas pelayanan kesehatan dengan target yang harus dicapai. Salah satu fungsi rumah sakit adalah melaksanakan program pemerintah dan mendukung tercapainya target target pembangunan nasional. Pada standar akreditasi ini Program Nasional (Prognas) meliputi:

1.	Peningkatan kesehatan ibu dan bayi.
2.	Penurunan angka kesakitan Tuberkulosis/TBC.
3.	Penurunan angka kesakitan HIV/AIDS.
4.	Penurunan prevalensi stunting dan wasting.
5.	Pelayanan Keluarga Berencana Rumah Sakit.

Pelaksanaan program nasional oleh rumah sakit diharapkan mampu meningkatkan akselerasi pencapaian target RPJMN bidang kesehatan sehingga upaya mingkatkan derajat kesehatan masyarakat meningkat segera terwujud.


## 1.	Peningkatan kesehatan ibu dan bayi  {-}

#### a.	Standar Prognas 1 {-}

Rumah sakit melaksanakan program PONEK 24 jam dan 7 (tujuh) hari seminggu.

#### b.	Maksud dan Tujuan Prognas 1 {-}

Rumah sakit  melaksanakan  program  PONEK  sesuai  dengan pedoman PONEK yang berlaku dengan langkah langkah sebagai berikut:

1.	Melaksanakan	dan	menerapkan	standar	pelayanan perlindungan ibu dan bayi secara terpadu.
2.	Mengembangkan kebijakan dan standar pelayanan ibu dan bayi.
3.	Meningkatkan kualitas pelayanan kesehatan ibu dan bayi.
4.	Meningkatkan kesiapan rumah sakit dalam melaksanakan fungsi pelayanan obstetric dan neonates termasuk pelayanan kegawatdaruratan (PONEK 24 jam).
5.	Meningkatkan fungsi rumah sakit sebagai model dan Pembina teknis dalam pelaksanaan IMD dan ASI Eksklusif serta Perawatan Metode Kanguru (PMK) pada BBLR
6.	Meningkatkan fungsi rumah sakit sebagai pusat rujukan pelayanan kesehatan ibu dan bayi bagi sarana pelayanan kesehatan lainnya.
7.	Melaksanakan pemantauan dan evaluasi pelaksanaan program RSSIB 10 langkah menyusui dan peningkatan kesehatan ibu
8.	Melakukan pemantauan dan analisis yang meliputi:

a.	Angka keterlambatan operasi section caesaria
b.	Angka kematian ibu dan anak
c.	Kejadian	tidak	dilakukannya	inisiasi	menyusui	dini (IMD) pada bayi baru lahir

#### c.	Elemen Penilaian Prognas 1 {-}

1.	Rumah sakit menetapkan regulasi tentang pelaksanaan PONEK 24 jam.
2.	Terdapat Tim PONEK yang ditetapkan oleh rumah sakit dengan rincian tugas dan tanggungjawabnya.
3.	Terdapat program kerja yang menjadi acuan dalam pelaksanaan program PONEK Rumah Sakit sesuai maksud dan tujuan.
4.	Terdapat bukti pelaksanaan program PONEK Rumah Sakit.
5.	Program PONEK Rumah Sakit dipantau dan dievaluasi secara rutin.

#### d.	Standar Prognas 1.1 {-}

Untuk meningkatkan efektifitas sistem rujukan maka Rumah sakit melakukan pembinaan kepada jejaring fasilitas Kesehatan rujukan yang ada.

#### e.	Maksud dan Tujuan Prognas 1.1 {-}

Salah satu tugas dari rumah sakit dengan kemampuan PONEK adalah melakukan pembinaan kepada jejaring rujukan seperti Puskesmas, Klinik bersalin, praktek perseorangan dan fasilitas pelayanan kesehatan lainnya. Pembinaan jejaring rujukan dapat dilakukan dengan mengadakan pelatihan kepada fasilitas kesehatan jejaring, berbagi pengalaman dalam  pelayanan  ibu dan anak serta peningkatanan kompetensi jejaring rujukan secara berkala. Rumah sakit memetakan jejaring rujukan yang ada dan membuat program pembinaan setiap tahun.

#### f.	Elemen Penilaian Standar Prognas 1.1 {-}

1.	Rumah	sakit	menetapkan	program	pembinaan	jejaring rujukan rumah sakit.
2.	Rumah	sakit	melakukan	pembinaan	terhadap	jejaring secara berkala.
3.	Telah	dilakukan	evaluasi	program	pembinaan	jejaring rujukan.

## 2.	Penurunan angka kesakitan Tuberkulosis/TBC  {-}

#### a.		Standar Prognas 2 {-}

Rumah sakit melaksanakan program penanggulangan tuberkulosis.

#### b.		Maksud dan Tujuan Prognas 2 {-}

Pemerintah mengeluarkan kebijakan penanggulangan tuberkulosis berupa upaya kesehatan yang mengutamakan aspek promotif, preventif, tanpa mengabaikan aspek kuratif dan rehabilitatif yang ditujukan untuk melindungi kesehatan masyarakat, menurunkan angka kesakitan, kecatatan atau kematian, memutuskan penularan mencegah resistensi obat dan mengurangi dampak negatif yang ditimbulkan akibat tuberkulosis.
Rumah sakit dalam melaksanakan penanggulangan tubekulosis melakukan kegiatan yang meliputi:

1.	Promosi kesehatan yang diarahkan untuk meningkatkan pengetahuan yang benar dan komprehensif mengenai pencegahan penularan, penobatan, pola hidup bersih dan sehat (PHBS) sehingga terjadi perubahan sikap dan perilaku sasaran yaitu pasien dan keluarga, pengunjung serta staf rumah sakit.
2.	Surveilans tuberkulosis, merupakan kegiatan memperoleh data epidemiologi yang diperlukan dalam sistem informasi program penanggulangan tuberkulosis, seperti pencatatan dan pelaporan tuberkulosis sensitif obat, pencatatan dan pelaporan tuberkulosis resistensi obat.
3.	Pengendalian faktor risiko tuberkulosis, ditujukan untuk mencegah, mengurangi penularan dan kejadian penyakit tuberkulosis, yang pelaksanaannya sesuai dengan pedoman pengendalian pencegahan infeksi tuberkulosis di rumah sakit pengendalian faktor risiko tuberkulosis, ditujukan untuk mencegah, mengurangi penularan dan kejadian penyakit tuberkulosis, yang pelaksanaannya sesuai dengan pedoman pengendalian pencegahan infeksi tuberkulosis di rumah sakit.
4.	Penemuan dan penanganan kasus tuberkulosis. 
Penemuan kasus tuberkulosis dilakukan  melalui  pasien yang datang kerumah sakit, setelah pemeriksaan, penegakan diagnosis, penetapan klarifikasi dan tipe pasien tuberkulosis. Sedangkan untuk penanganan kasus dilaksanakan sesuai tata laksana pada pedoman nasional pelayanan kedokteran tuberkulosis dan standar lainnya sesuai dengan peraturan perundang- undangan.
5.	Pemberian kekebalan.
Pemberian kekebalan dilakukan melalui pemberian imunisasi BCG terhadap bayi dalam upaya penurunan risiko tingkat pemahaman tuberkulosis sesuai dengan peraturan perundang-undangan.
6.	Pemberian obat pencegahan.
Pemberian obat pencegahan selama 6 (enam) bulan yang ditujukan pada anak usia dibawah 5 (lima) tahun yang kontak erat dengan pasien tuberkulosis aktif; orang dengan HIV dan AIDS (ODHA) yang tidak terdiagnosis tuberkulosis; populasi tertentu lainnya sesuai peraturan perundang-undangan.

Untuk menjalankan kegiatan tersebut maka rumah sakit dapat membentuk tim/panitia pelaksana program TB Paru Rumah Sakit.

#### c.	Elemen Penilaian Prognas 2 {-}

1.	Rumah sakit menerapkan regulasi tentang pelaksanaan penanggulangan tuberkulosis di rumah sakit.
2.	Direktur menetapkan tim TB Paru Rumah sakit beserta program kerjanya.
3.	Ada bukti pelaksanaan promosi kesehatan, surveilans dan upaya pencegahan tuberkulosis
4.	Tersedianya laporan pelaksanaan promosi Kesehatan.

#### d.	Standar Prognas 2.1 {-}

Rumah sakit menyediakan sarana dan prasarana pelayanan tuberkulosis sesuai peraturan perundang-undangan.

#### e.	Maksud dan Tujuan Prognas 2.1 {-}

Dalam melaksanakan pelayanan kepada penderita TB Paru dan program TB Paru di rumah sakit, maka harus tersedia sarana dan prasarana yang memenuhi syarat pelayanan TB Paru sesuai dengan Pedoman Pelayanan TB Paru.

#### f.	Elemen Penilaian Prognas 2.1 {-}

1.	Tersedia ruang pelayanan rawat jalan yang memenuhi pedoman pencegahan dan pengendalian infeksi tuberkulosis.
2.	Bila rumah sakit memberikan pelayanan rawat inap bagi pasien tuberkulosis paru dewasa maka rumah sakit harus memiliki ruang rawat inap yang memenuhi pedoman pencegahan danpengendalian infeksi tuberkulosis.
3.	Tersedia ruang pengambilan spesimen sputum yang memenuhi pedoman pencegahan dan pengendalian infeksi tuberkulosis.

#### g.	Standar Prognas 2.2 {-}

Rumah sakit telah melaksanakan pelayanan tuberkulosis dan upaya pengendalian faktor risiko tuberkulosis sesuai peraturan perundang-undangan.

#### h.	Elemen Penilaian Prognas 2.2 {-}

1.	Rumah	sakit	telah	menerapkan	kepatuhan	staf	medis terhadap panduan praktik klinis tuberkulosis.
2.	Rumah sakit merencanakan dan mengadakan penyediaan Obat Anti Tuberkulosis.
3.	Rumah	sakit	melaksanakan	pelayanan	TB	MDR	(bagi rumah sakit rujukan TB MDR).
4.	Rumah	sakit	melaksanakan	pencatatan	dan	pelaporan kasus TB Paru sesuai ketentuan.

## 3.	Penurunan angka kesakitan HIV/AIDS  {-}

#### a.	Standar Prognas 3 {-}

Rumah sakit melaksanakan penanggulangan HIV/AIDS sesuai dengan peraturan perundang-undangan.

#### b.	Maksud dan Tujuan Prognas 3 {-}

Rumah sakit dalam melaksanakan penanggulangan HIV/AIDS sesuai standar pelayanan bagi rujukan orang dengan HIV/AIDS (ODHA) dan satelitnya dengan langkah-langkah sebagai berikut:

1.	Meningkatkan fungsi pelayanan Voluntary Counseling and Testing (VCT).
2.	Meningkatkan fungsi pelayanan Antiretroviral Therapy (ART) atau bekerja sama dengan rumah sakit yang ditunjuk.
3.	Meningkatkan fungsi pelayanan Infeksi Oportunistik (IO).
4.	Meningkatkan fungsi pelayanan pada ODHA dengan factor risiko Injection Drug Use (IDU).
5.	Meningkatkan fungsi pelayanan penunjang yang meliputi pelayanan gizi, laboratorium dan radiologi, pencatatan dan pelaporan.

#### c.	Elemen Penilaian Prognas 3 {-}

1.	Rumah	sakit	telah	melaksanakan	kebijakan	program penanggulangan HIV/AIDS sesuai ketentuan perundangan.
2.	Rumah sakit telah menerapkan fungsi rujukan HIV/AIDS pada rumah sakit sesuai dengan kebijakan yang berlaku.
3.	Rumah sakit melaksanakan pelayanan PITC dan PMTC.
4.	Rumah sakit memberikan pelayanan ODHA dengan faktor risiko IO.
5.	Rumah sakit merencanakan dan mengadakan penyediaan ART.
6.	Rumah sakit melakukan pemantauan dan evaluasi program penanggulangan HIV/AIDS.

## 4.	Penurunan prevalensi stunting dan wasting  {-}

#### a.	Standar Prognas 4 {-}

Rumah	Sakit	melaksanakan	program	penurunan	prevalensi
stunting dan wasting.

#### b.	Standar Prognas 4.1 {-}

Rumah Sakit melakukan edukasi, pendampingan intervensi dan pengelolaan gizi serta penguatan jejaring rujukan kepada rumah sakit kelas di bawahnya dan FKTP di wilayahnya serta rujukan masalah gizi.

#### c.	Maksud dan Tujuan Prognas 4 dan Prognas 4.1 {-}

Tersedia regulasi penyelenggaraan program penurunan prevalensi stunting dan prevalensi wasting di rumah sakit yang meliputi:

1.	Program  penurunan   prevalensi   stunting   dan   prevalensi
2.	wasting.
3.	Panduan tata laksana.
4.	Organisasi pelaksana program terdiri dari tenaga kesehatan yang kompeten dari unsur:
a.	Staf Medis.
b.	Staf Keperawatan.
c.	Staf Instalasi Farmasi.
d.	Staf Instalasi Gizi.
e.	Tim Tumbuh Kembang.
f.	Tim Humas Rumah Sakit.

Organisasi program penurunan prevalensi stunting dan wasting dipimpin oleh staf medis atau dokter spesialis anak. Rumah sakit menyusun program penurunan prevalensi stunting dan wasting di rumah sakit terdiri dari:

1.	Peningkatan pemahaman dan kesadaran seluruh staf, pasien dan keluarga tentang masalah stunting dan wasting;
2.	Intervensi spesifik di rumah sakit;
3.	Penerapan Rumah Sakit Sayang Ibu Bayi;
4.	Rumah sakit  sebagai  pusat  rujukan  kasus  stunting  dan
5.	wasting;
6.	Rumah sakit sebagai pendamping klinis dan manajemen serta merupakan jejaring rujukan
7.	Program pemantauan dan evaluasi.

Penurunan	prevalensi	stunting	dan	prevalensi	wasting
meliputi:

1.	Kegiatan sosialisasi dan pelatihan staf tenaga kesehatan rumah sakit tentang Program Penurunan Stunting dan Wasting.
2.	Peningkatan efektifitas intervensi spesifik.

a.	Program 1000 HPK.
b.	Suplementasi Tablet Besi Folat pada ibu hamil.
c.	Pemberian Makanan Tambahan (PMT) pada ibu hamil.
d.	Promosi dan konseling IMD dan ASI Eksklusif.
e.	Pemberian Makanan Bayi dan Anak (PMBA).
f.	Pemantauan	Pertumbuhan	(Pelayanan	Tumbuh Kembang bayi dan balita).
g.	Pemberian Imunisasi.
h.	Pemberian Makanan Tambahan Balita Gizi Kurang.
i.	Pemberian Vitamin A.
j.	Pemberian taburia pada Baduta (0-23 bulan).
k.	Pemberian obat cacing pada ibu hamil.

3.	Penguatan sistem surveilans gizi

a.	Tata laksana tim asuhan gizi  meliputi  Tata  laksana Gizi Stunting, Tata Laksana Gizi Kurang, Tata Laksana Gizi Buruk (Pedoman Pencegahan dan Tata Laksana Gizi Buruk pada Balita).
b.	Pencatatan dan Pelaporan kasus masalah gizi melalui aplikasi ePPGBM (Aplikasi Pencatatan dan Pelaporan Gizi Berbasis Masyarakat).
c.	Melakukan evaluasi pelayanan, audit kesakitan dan kematian, pencatatan dan pelaporan gizi buruk dan stunting dalam Sistem Informasi Rumah Sakit (SIRS).

Rumah sakit melaksanakan pelayanan sebagai pusat rujukan kasus stunting dan kasus wasting dengan menyiapkan sebagai:

1.	Rumah sakit sebagai pusat rujukan kasus stunting untuk memastikan kasus, penyebab dan tata laksana lanjut oleh dokter spesialis anak.
2.	Rumah sakit sebagai pusat rujukan balita gizi buruk dengan komplikasi medis.
3.	Rumah sakit dapat melaksanakan pendampingan klinis dan manajemen serta penguatan jejaring rujukan kepada rumah sakit dengan kelas di bawahnya dan Fasilitas Kesehatan Tingkat Pertama (FKTP) di wilayahnya dalam tata laksana stunting dan gizi buruk.

#### d.	Elemen Penilaian Prognas 4 {-}

1.	Rumah	sakit	telah	menetapkan	kebijakan	tentang pelaksanaan program gizi.
2.	Terdapat	tim	untuk	program	penurunan	prevalensi stunting dan wasting di rumah sakit.
3.	Rumah sakit telah menetapkan sistem  rujukan  untuk kasus gangguan gizi yang perlu penanganan lanjut.

#### e.	Elemen Penilaian Prognas 4.1 {-}

1.	Rumah sakit membuktikan telah melakukan pendampingan intervensi dan pengelolaan gizi serta penguatan jejaring rujukan kepada rumah sakit kelas di bawahnya dan FKTP di wilayahnya serta rujukan masalah gizi.
2.	Rumah sakit telah menerapkan sistem pemantauan dan evaluasi, bukti pelaporan, dan analisis.

## 5.	Pelayanan Keluarga Berencana Rumah Sakit  {-}

#### a.	Standar Prognas 5 {-}

Rumah sakit melaksanakan program pelayanan keluarga berencana dan kesehatan reproduksi di rumah sakit beserta pemantauan dan evaluasinya.

#### b.	Standar Prognas 5.1 {-}

Rumah sakit menyiapkan sumber daya untuk penyelenggaraan pelayanan keluarga dan kesehatan reproduksi.

#### c.	Maksud dan Tujuan Prognas 5 dan Prognas 5.1 {-}

Pelayanan	Keluarga	Berencana	di	Rumah	Sakit	(PKBRS) merupakan bagian dari program keluarga berencana (KB), yang sangat berperan dalam menurunkan angka kematian ibu dan percepatan penurunan stunting. Kunci keberhasilan PKBRS adalah ketersediaan alat dan obat kontrasepsi, sarana penunjang pelayanan kontrasepsi dan tenaga kesehatan yang sesuai kompetensi serta manjemen yang handal. Rumah sakit dalam melaksanakan PKBRS sesuai dengan pedoman pelayanan KB yang berlaku, dengan langkah-langkah pelaksanaan sebagai berikut:

1.	Melaksanakan dan menerapkan standar pelayanaan KB secara terpadu dan paripurna.
2.	Mengembangkan kebijakan dan Standar Prosedur Operasional (SPO) pelayanan KB dan meningkatkan kualitas pelayanan KB.
3.	Meningkatkan kesiapan rumah sakit dalam melaksanakan PKBRS termasuk pelayanan KB Pasca Persalinan dan Pasca Keguguran.
4.	Meningkatkan fungsi rumah sakit sebagai model dan pembinaan teknis dalam melaksanakan PKBRS.
5.	Meningkatkan fungsi rumah sakit sebagai pusat rujukan pelayanan KB bagi sarana pelayanan kesehatan lainnya.
6.	Melaksanakan sistem pemantauan dan evaluasi pelaksanaan PKBRS.
7.	Adanya regulasi rumah sakit yang menjamin pelaksanaan PKBRS, meliputi SPO pelayanan KB per metode kontrasepsi termasuk pelayanan KB Pasca Persalinan dan Pasca Keguguran.
8.	Upaya peningkatan PKBRS masuk dalam rencana strategis (Renstra) dan rencana kerja anggaran (RKA) rumah sakit.
9.	Tersedia ruang pelayanan yang memenuhi persyaratan untuk PKBRS antara lain ruang konseling dan ruang pelayanan KB.
10.	Pembentukan tim PKBR serta program kerja dan bukti pelaksanaanya.
11.	Terselenggara kegiatan peningkatan kapasitas untuk meningkatkan kemampuan pelayanan PKBRS, termasuk KB Pasca Persalinan dan Pasca Keguguran.
12.	Pelaksanaan rujukan sesuai dengan ketentuan peraturan perundangan-undangan.
13.	Pelaporan dan analisis meliputi:

a.	Ketersediaan semua jenis alat dan obat kontrasepsi sesuai dengan kapasitas rumah sakit dan kebutuhan pelayanan KB.
b.	Ketersediaan sarana penunjang pelayanan KB.
c.	Ketersediaan tenaga kesehatan yang memberikan pelayanan KB.
d.	Angka capaian pelayanan KB per metode kontrasepsi, baik Metode Kontrasepsi Jangka Panjang (MKJP) dan Non MKJP.
e.	Angka capaian pelayanan KB Pasca Persalinan dan Pasca Keguguran.
f.	Kejadian tidak dilakukannya KB Pasca Persalinan pada ibu baru bersalin dan KB Pasca Keguguran pada Ibu pasca keguguran.

#### d.	Elemen Penilaian Prognas 5 {-}

1.	Rumah	sakit	telah	menetapkan	kebijakan	tentang pelaksanaan PKBRS.
2.	Terdapat tim PKBRS yang ditetapkan oleh direktur disertai program kerjanya.
3.	Rumah	sakit	telah	melaksanakan	program	KB	Pasca Persalinan dan Pasca Keguguran.
4.	Rumah sakit telah melakukan pemantauan dan evaluasi pelaksanaan PKBRS.

#### e.	Elemen Penilaian Prognas 5.1 {-}

1.	Rumah sakit telah menyediakan alat dan obat kontrasepsi dan sarana penunjang pelayanan KB.
2.	Rumah sakit menyediakan layanan konseling bagi peserta dan calon peserta program KB.
3.	Rumah sakit telah merancang dan menyediakan ruang pelayanan KB yang memadai.